### ISSUE TITLE
Parameterised issues: Unable to select non-researched items

### ISSUE THREAD

**Issue by Muramas** [steven-tk/factorio-blueprints#1]
As much as parameterization is sometimes nice because you might not want something or more of something else...

One issue I have with it is that if you don't have that tech you can't choose that option at all, even with the "Show all items in selection lists" enabled. This means that for the options that the blueprint suggests, you can't pre-plan your mall.

![image](https://github.com/user-attachments/assets/7d1e73b8-65b8-49ff-b7c0-e7f958030404)

Here I am unable to select laser turrets

![image](https://github.com/user-attachments/assets/1753d905-1493-42f2-8a57-cbd6d298bf58)

**Comment by steven-tk** [comment]
Sorry for the late reply - somehow missed the notification.
Given that the devs recently introduced the inactive state for assemblers with unresearched recipes, this seems to be an oversight on their end. I'd recommend opening a bug report on their forums: https://forums.factorio.com/viewforum.php?f=7

Since you can't place them without choosing something i'd suggest putting parameters in them again as a quick workaround (I see you already have the option toggled to see them in selection lists).
Beyond that there is hardly something I can do if i want to keep the benefit of parameters- and i do :)

That aside you likely need *some* turrets anyways before unlocking lasers so might as well pick gun turrets, no?

**Comment by Muramas** [comment]
Until it is fixed you could always do a defined version where it has lasers and turrets and another that is parameterized, the only other one is chests and barrels but I don't think that is an issue at all.

**Comment by steven-tk** [comment]
I'd rather wait till it's fixed on wube's side.
The whole point of parameters is letting the user choose. Choosing for you by having a 2nd defined blueprint defeats that purpose  - which is kinda the whole design basis of the mall :)

Not to mention so far you are the first and only person that criticised that and while I don't mind making changes, I still have to balance what you ask for with the consequences of adding that for everyone else. Base on my past experiences I would expect two similar blueprints to be confusing more people than it would help circumvent this very niche issue.

Besides there's an obvious solution: If you don't have lasers yet just use 2x gun turrets and switch later. They will remain viable later on anyways due to space platforms so it's not wasted if you build a few too many early on.
I don't know at which point in the game you are, whether you even like lasers or whether you wanna use lasers exclusively for your defences (spoiler: one assembler isn't enough then if you expand aggressively). So making a choice for you will always be subpar. Personally I switch those two assemblers more than once during the game depending on what tech-level/stage i am at.
If you don't like that then you can always keep the assembler empty by using a placeholder such as parameters or something that can't be build due to needing different materials than what is supplied.
