### ISSUE TITLE
Concrete missing

### ISSUE THREAD

**Issue by Muramas** [steven-tk/factorio-blueprints#2]
It seems that concrete is missing from the build which means that reactors and centrifuges don't get made. I assume that this one chest is a requester chest but instead it is a steel chest. It might make sense to keep it as a requester ghost so that it can be setup to request when you can make it.

![image](https://github.com/user-attachments/assets/b8d2301a-d2b4-432a-a340-b77f4f922fa4)

**Comment by steven-tk** [comment]
Thanks for the report! 
Anyways maybe one of my tweaks to the module accidentally broke it? I will check it out after breakfast and upload a fix if that's the case.

However there should be a wooden chest which is meant to be upgraded later on via the included upgrade planner into a requester chests - as well as act as a temporary dumping chest for concrete.
Alternatively you could always replace it with an underground belt and sideload the concrete - that is something that will be fixed in the next major version via it's fundamental re-design.

**Comment by steven-tk** [comment]
As I said it's supposed to be a wooden chest so I reckon something went wrong on your end somehow. (see Pic)
Regardlessly it'll be improved in the next major release :)


<img width="1113" alt="Screenshot 2024-11-22 at 05 47 38" src="https://github.com/user-attachments/assets/5d6a1344-4e1d-4a90-92a5-362624124b19">

**Comment by steven-tk** [comment]
As I said it's supposed to be a wooden chest so I reckon something went wrong on your end somehow. (see Pic)
Regardlessly it'll be improved in the next major release :)

Edit:
Make sure the nuclear module is at the end of the mall otherwise it’ll starve any following module of steel and copper while it is producing. :)

<img width="1113" alt="Screenshot 2024-11-22 at 05 47 38" src="https://github.com/user-attachments/assets/7cb5dbcd-54fa-49ef-9dd0-c309749132b3">
